<?xml version="1.0" encoding="utf-8"?><Database Name="Billing" Class="InvoicesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-C01B2L4;Initial Catalog=Billing;Integrated Security=True;Persist Security Info=True" SettingsObjectName="DataAccess.Properties.Settings" SettingsPropertyName="BillingConnectionString1" Provider="System.Data.SqlClient" />
  <Function Name="dbo.sp_createInvoice" Method="sp_createInvoice">
    <Parameter Name="usrID" Type="System.Decimal" DbType="Decimal(18,0)" />
    <Parameter Name="price" Type="System.Decimal" DbType="Decimal(18,0)" />
    <Parameter Name="prod_stock" Type="System.Decimal" DbType="Decimal(18,0)" />
    <Parameter Name="prodID" Type="System.Decimal" DbType="Decimal(18,0)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_updateInvoices" Method="sp_updateInvoices">
    <Parameter Name="bllID" Type="System.Decimal" DbType="Decimal(18,0)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_deleteInvoice" Method="sp_deleteInvoice">
    <Parameter Name="bllID" Type="System.Decimal" DbType="Decimal(18,0)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_getInvoicesFilters" Method="sp_getInvoicesFilters">
    <Parameter Name="pageSize" Type="System.Int32" DbType="Int" />
    <Parameter Name="pageNumber" Type="System.Int32" DbType="Int" />
    <Parameter Name="orderBy" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="orderDirection" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="totalRecords" Type="System.Int32" DbType="Int" Direction="InOut" />
    <ElementType Name="sp_getInvoicesFiltersResult">
      <Column Name="bllID" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="usrID" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="bll_date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="bll_status" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="bll_create_at" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="bll_update_at" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="usr_name" Type="System.String" DbType="VarChar(80) NOT NULL" CanBeNull="false" />
      <Column Name="usr_surname" Type="System.String" DbType="VarChar(80) NOT NULL" CanBeNull="false" />
      <Column Name="usr_document_number" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="dprd_quantity" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="dprd_price" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
</Database>