#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Billing")]
	public partial class InvoicesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    #endregion
		
		public InvoicesDataContext() : 
				base(global::DataAccess.Properties.Settings.Default.BillingConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public InvoicesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public InvoicesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public InvoicesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public InvoicesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_createInvoice")]
		public int sp_createInvoice([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Decimal(18,0)")] System.Nullable<decimal> usrID, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Decimal(18,0)")] System.Nullable<decimal> price, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Decimal(18,0)")] System.Nullable<decimal> prod_stock, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Decimal(18,0)")] System.Nullable<decimal> prodID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), usrID, price, prod_stock, prodID);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_updateInvoices")]
		public int sp_updateInvoices([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Decimal(18,0)")] System.Nullable<decimal> bllID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), bllID);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_deleteInvoice")]
		public int sp_deleteInvoice([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Decimal(18,0)")] System.Nullable<decimal> bllID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), bllID);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_getInvoicesFilters")]
		public ISingleResult<sp_getInvoicesFiltersResult> sp_getInvoicesFilters([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> pageSize, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> pageNumber, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string orderBy, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string orderDirection, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> totalRecords)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), pageSize, pageNumber, orderBy, orderDirection, totalRecords);
			totalRecords = ((System.Nullable<int>)(result.GetParameterValue(4)));
			return ((ISingleResult<sp_getInvoicesFiltersResult>)(result.ReturnValue));
		}
	}
	
	public partial class sp_getInvoicesFiltersResult
	{
		
		private decimal _bllID;
		
		private decimal _usrID;
		
		private System.DateTime _bll_date;
		
		private string _bll_status;
		
		private System.DateTime _bll_create_at;
		
		private System.Nullable<System.DateTime> _bll_update_at;
		
		private string _usr_name;
		
		private string _usr_surname;
		
		private decimal _usr_document_number;
		
		private decimal _dprd_quantity;
		
		private decimal _dprd_price;
		
		public sp_getInvoicesFiltersResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bllID", DbType="Decimal(18,0) NOT NULL")]
		public decimal bllID
		{
			get
			{
				return this._bllID;
			}
			set
			{
				if ((this._bllID != value))
				{
					this._bllID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usrID", DbType="Decimal(18,0) NOT NULL")]
		public decimal usrID
		{
			get
			{
				return this._usrID;
			}
			set
			{
				if ((this._usrID != value))
				{
					this._usrID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bll_date", DbType="DateTime NOT NULL")]
		public System.DateTime bll_date
		{
			get
			{
				return this._bll_date;
			}
			set
			{
				if ((this._bll_date != value))
				{
					this._bll_date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bll_status", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string bll_status
		{
			get
			{
				return this._bll_status;
			}
			set
			{
				if ((this._bll_status != value))
				{
					this._bll_status = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bll_create_at", DbType="DateTime NOT NULL")]
		public System.DateTime bll_create_at
		{
			get
			{
				return this._bll_create_at;
			}
			set
			{
				if ((this._bll_create_at != value))
				{
					this._bll_create_at = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bll_update_at", DbType="DateTime")]
		public System.Nullable<System.DateTime> bll_update_at
		{
			get
			{
				return this._bll_update_at;
			}
			set
			{
				if ((this._bll_update_at != value))
				{
					this._bll_update_at = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usr_name", DbType="VarChar(80) NOT NULL", CanBeNull=false)]
		public string usr_name
		{
			get
			{
				return this._usr_name;
			}
			set
			{
				if ((this._usr_name != value))
				{
					this._usr_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usr_surname", DbType="VarChar(80) NOT NULL", CanBeNull=false)]
		public string usr_surname
		{
			get
			{
				return this._usr_surname;
			}
			set
			{
				if ((this._usr_surname != value))
				{
					this._usr_surname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usr_document_number", DbType="Decimal(18,0) NOT NULL")]
		public decimal usr_document_number
		{
			get
			{
				return this._usr_document_number;
			}
			set
			{
				if ((this._usr_document_number != value))
				{
					this._usr_document_number = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dprd_quantity", DbType="Decimal(18,0) NOT NULL")]
		public decimal dprd_quantity
		{
			get
			{
				return this._dprd_quantity;
			}
			set
			{
				if ((this._dprd_quantity != value))
				{
					this._dprd_quantity = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dprd_price", DbType="Decimal(18,0) NOT NULL")]
		public decimal dprd_price
		{
			get
			{
				return this._dprd_price;
			}
			set
			{
				if ((this._dprd_price != value))
				{
					this._dprd_price = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
