#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Billing")]
	public partial class ProductsDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    #endregion
		
		public ProductsDataContext() : 
				base(global::DataAccess.Properties.Settings.Default.BillingConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public ProductsDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ProductsDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ProductsDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ProductsDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_getProduct")]
		public ISingleResult<sp_getProductResult> sp_getProduct([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Decimal(18,0)")] System.Nullable<decimal> prodID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), prodID);
			return ((ISingleResult<sp_getProductResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_getProductsFilters")]
		public ISingleResult<sp_getProductsFiltersResult> sp_getProductsFilters([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Decimal(18,0)")] System.Nullable<decimal> prod_code, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(80)")] string prod_name, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> pageSize, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> pageNumber, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string orderBy, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string orderDirection, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> totalRecords)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), prod_code, prod_name, pageSize, pageNumber, orderBy, orderDirection, totalRecords);
			totalRecords = ((System.Nullable<int>)(result.GetParameterValue(6)));
			return ((ISingleResult<sp_getProductsFiltersResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_createProducts")]
		public int sp_createProducts([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Decimal(18,0)")] System.Nullable<decimal> prod_code, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(80)")] string prod_name, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Decimal(18,0)")] System.Nullable<decimal> prod_price, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Decimal(18,0)")] System.Nullable<decimal> prod_stock)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), prod_code, prod_name, prod_price, prod_stock);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_updateProducts")]
		public int sp_updateProducts([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Decimal(18,0)")] System.Nullable<decimal> prodID, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Decimal(18,0)")] System.Nullable<decimal> prod_stock)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), prodID, prod_stock);
			return ((int)(result.ReturnValue));
		}
	}
	
	public partial class sp_getProductResult
	{
		
		private decimal _prodID;
		
		private decimal _prod_code;
		
		private string _prod_name;
		
		private decimal _prod_price;
		
		private decimal _prod_stock;
		
		private string _prod_status;
		
		public sp_getProductResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_prodID", DbType="Decimal(18,0) NOT NULL")]
		public decimal prodID
		{
			get
			{
				return this._prodID;
			}
			set
			{
				if ((this._prodID != value))
				{
					this._prodID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_prod_code", DbType="Decimal(18,0) NOT NULL")]
		public decimal prod_code
		{
			get
			{
				return this._prod_code;
			}
			set
			{
				if ((this._prod_code != value))
				{
					this._prod_code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_prod_name", DbType="VarChar(80) NOT NULL", CanBeNull=false)]
		public string prod_name
		{
			get
			{
				return this._prod_name;
			}
			set
			{
				if ((this._prod_name != value))
				{
					this._prod_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_prod_price", DbType="Decimal(18,0) NOT NULL")]
		public decimal prod_price
		{
			get
			{
				return this._prod_price;
			}
			set
			{
				if ((this._prod_price != value))
				{
					this._prod_price = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_prod_stock", DbType="Decimal(18,0) NOT NULL")]
		public decimal prod_stock
		{
			get
			{
				return this._prod_stock;
			}
			set
			{
				if ((this._prod_stock != value))
				{
					this._prod_stock = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_prod_status", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string prod_status
		{
			get
			{
				return this._prod_status;
			}
			set
			{
				if ((this._prod_status != value))
				{
					this._prod_status = value;
				}
			}
		}
	}
	
	public partial class sp_getProductsFiltersResult
	{
		
		private decimal _prodID;
		
		private string _prod_name;
		
		private decimal _prod_code;
		
		private decimal _prod_price;
		
		private decimal _prod_stock;
		
		private string _prod_status;
		
		private System.DateTime _prod_create_at;
		
		private System.Nullable<System.DateTime> _prod_update_at;
		
		public sp_getProductsFiltersResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_prodID", DbType="Decimal(18,0) NOT NULL")]
		public decimal prodID
		{
			get
			{
				return this._prodID;
			}
			set
			{
				if ((this._prodID != value))
				{
					this._prodID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_prod_name", DbType="VarChar(80) NOT NULL", CanBeNull=false)]
		public string prod_name
		{
			get
			{
				return this._prod_name;
			}
			set
			{
				if ((this._prod_name != value))
				{
					this._prod_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_prod_code", DbType="Decimal(18,0) NOT NULL")]
		public decimal prod_code
		{
			get
			{
				return this._prod_code;
			}
			set
			{
				if ((this._prod_code != value))
				{
					this._prod_code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_prod_price", DbType="Decimal(18,0) NOT NULL")]
		public decimal prod_price
		{
			get
			{
				return this._prod_price;
			}
			set
			{
				if ((this._prod_price != value))
				{
					this._prod_price = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_prod_stock", DbType="Decimal(18,0) NOT NULL")]
		public decimal prod_stock
		{
			get
			{
				return this._prod_stock;
			}
			set
			{
				if ((this._prod_stock != value))
				{
					this._prod_stock = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_prod_status", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string prod_status
		{
			get
			{
				return this._prod_status;
			}
			set
			{
				if ((this._prod_status != value))
				{
					this._prod_status = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_prod_create_at", DbType="DateTime NOT NULL")]
		public System.DateTime prod_create_at
		{
			get
			{
				return this._prod_create_at;
			}
			set
			{
				if ((this._prod_create_at != value))
				{
					this._prod_create_at = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_prod_update_at", DbType="DateTime")]
		public System.Nullable<System.DateTime> prod_update_at
		{
			get
			{
				return this._prod_update_at;
			}
			set
			{
				if ((this._prod_update_at != value))
				{
					this._prod_update_at = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
