#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Billing")]
	public partial class UsersDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    #endregion
		
		public UsersDataContext() : 
				base(global::DataAccess.Properties.Settings.Default.BillingConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public UsersDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public UsersDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public UsersDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public UsersDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_createUser")]
		public int sp_createUser([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(80)")] string usr_name, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(80)")] string usr_surname, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Decimal(18,0)")] System.Nullable<decimal> usr_document_number, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(80)")] string usr_email, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Decimal(18,0)")] System.Nullable<decimal> usr_age)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), usr_name, usr_surname, usr_document_number, usr_email, usr_age);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_getUsersFilters")]
		public ISingleResult<sp_getUsersFiltersResult> sp_getUsersFilters([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(80)")] string usr_name, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(80)")] string usr_surname, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Decimal(18,0)")] System.Nullable<decimal> usr_document_number, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> pageSize, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> pageNumber, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string orderBy, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string orderDirection, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> totalRecords)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), usr_name, usr_surname, usr_document_number, pageSize, pageNumber, orderBy, orderDirection, totalRecords);
			totalRecords = ((System.Nullable<int>)(result.GetParameterValue(7)));
			return ((ISingleResult<sp_getUsersFiltersResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_getUser")]
		public ISingleResult<sp_getUserResult> sp_getUser([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Decimal(18,0)")] System.Nullable<decimal> usr_document_number)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), usr_document_number);
			return ((ISingleResult<sp_getUserResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_updateUser")]
		public int sp_updateUser([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Decimal(18,0)")] System.Nullable<decimal> usrID, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(80)")] string usr_name, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(80)")] string usr_surname)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), usrID, usr_name, usr_surname);
			return ((int)(result.ReturnValue));
		}
	}
	
	public partial class sp_getUsersFiltersResult
	{
		
		private decimal _usrID;
		
		private string _usr_name;
		
		private string _usr_surname;
		
		private decimal _usr_document_number;
		
		private string _usr_email;
		
		private decimal _usr_age;
		
		private string _usr_status;
		
		private System.DateTime _usr_create_at;
		
		private System.Nullable<System.DateTime> _usr_update_at;
		
		public sp_getUsersFiltersResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usrID", DbType="Decimal(18,0) NOT NULL")]
		public decimal usrID
		{
			get
			{
				return this._usrID;
			}
			set
			{
				if ((this._usrID != value))
				{
					this._usrID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usr_name", DbType="VarChar(80) NOT NULL", CanBeNull=false)]
		public string usr_name
		{
			get
			{
				return this._usr_name;
			}
			set
			{
				if ((this._usr_name != value))
				{
					this._usr_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usr_surname", DbType="VarChar(80) NOT NULL", CanBeNull=false)]
		public string usr_surname
		{
			get
			{
				return this._usr_surname;
			}
			set
			{
				if ((this._usr_surname != value))
				{
					this._usr_surname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usr_document_number", DbType="Decimal(18,0) NOT NULL")]
		public decimal usr_document_number
		{
			get
			{
				return this._usr_document_number;
			}
			set
			{
				if ((this._usr_document_number != value))
				{
					this._usr_document_number = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usr_email", DbType="VarChar(80) NOT NULL", CanBeNull=false)]
		public string usr_email
		{
			get
			{
				return this._usr_email;
			}
			set
			{
				if ((this._usr_email != value))
				{
					this._usr_email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usr_age", DbType="Decimal(18,0) NOT NULL")]
		public decimal usr_age
		{
			get
			{
				return this._usr_age;
			}
			set
			{
				if ((this._usr_age != value))
				{
					this._usr_age = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usr_status", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string usr_status
		{
			get
			{
				return this._usr_status;
			}
			set
			{
				if ((this._usr_status != value))
				{
					this._usr_status = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usr_create_at", DbType="DateTime NOT NULL")]
		public System.DateTime usr_create_at
		{
			get
			{
				return this._usr_create_at;
			}
			set
			{
				if ((this._usr_create_at != value))
				{
					this._usr_create_at = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usr_update_at", DbType="DateTime")]
		public System.Nullable<System.DateTime> usr_update_at
		{
			get
			{
				return this._usr_update_at;
			}
			set
			{
				if ((this._usr_update_at != value))
				{
					this._usr_update_at = value;
				}
			}
		}
	}
	
	public partial class sp_getUserResult
	{
		
		private decimal _usrID;
		
		private decimal _usr_document_number;
		
		private string _usr_name;
		
		private string _usr_surname;
		
		private string _usr_email;
		
		private decimal _usr_age;
		
		private string _usr_status;
		
		private System.DateTime _usr_create_at;
		
		private System.Nullable<System.DateTime> _usr_update_at;
		
		public sp_getUserResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usrID", DbType="Decimal(18,0) NOT NULL")]
		public decimal usrID
		{
			get
			{
				return this._usrID;
			}
			set
			{
				if ((this._usrID != value))
				{
					this._usrID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usr_document_number", DbType="Decimal(18,0) NOT NULL")]
		public decimal usr_document_number
		{
			get
			{
				return this._usr_document_number;
			}
			set
			{
				if ((this._usr_document_number != value))
				{
					this._usr_document_number = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usr_name", DbType="VarChar(80) NOT NULL", CanBeNull=false)]
		public string usr_name
		{
			get
			{
				return this._usr_name;
			}
			set
			{
				if ((this._usr_name != value))
				{
					this._usr_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usr_surname", DbType="VarChar(80) NOT NULL", CanBeNull=false)]
		public string usr_surname
		{
			get
			{
				return this._usr_surname;
			}
			set
			{
				if ((this._usr_surname != value))
				{
					this._usr_surname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usr_email", DbType="VarChar(80) NOT NULL", CanBeNull=false)]
		public string usr_email
		{
			get
			{
				return this._usr_email;
			}
			set
			{
				if ((this._usr_email != value))
				{
					this._usr_email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usr_age", DbType="Decimal(18,0) NOT NULL")]
		public decimal usr_age
		{
			get
			{
				return this._usr_age;
			}
			set
			{
				if ((this._usr_age != value))
				{
					this._usr_age = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usr_status", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string usr_status
		{
			get
			{
				return this._usr_status;
			}
			set
			{
				if ((this._usr_status != value))
				{
					this._usr_status = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usr_create_at", DbType="DateTime NOT NULL")]
		public System.DateTime usr_create_at
		{
			get
			{
				return this._usr_create_at;
			}
			set
			{
				if ((this._usr_create_at != value))
				{
					this._usr_create_at = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usr_update_at", DbType="DateTime")]
		public System.Nullable<System.DateTime> usr_update_at
		{
			get
			{
				return this._usr_update_at;
			}
			set
			{
				if ((this._usr_update_at != value))
				{
					this._usr_update_at = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
